spring.application.name=moviebooking
   spring.datasource.url=jdbc:mysql://localhost:3306/moviebooking_db
   spring.datasource.username=root
   spring.datasource.password=priya@@@2007
   spring.jpa.hibernate.ddl-auto=update
   spring.jpa.show-sql=true
